print("***************************Menú Login de jugadores***************************")
print("1) Registro de nuevo jugador.")
print("2) Inicio sesion jugador.")
print("Ingrese una opcion valida: 1")
print("Cree el nombre de jugador nuevo: pabliotGamer")
print("Ingrese nombre de jugador: pabliotGamer")
print("***************************Login exitoso***************************")
print("Bienvenido pabliotGamer.")
print("Nivel: 987")
print("Puntaje: 66.587")
print("Equipo: En solitario")
print("Inventario: \n{[""AK-66""]: 30(160)  \n[""M9""]: 7(21) \n[""Botiquin""]: 1(3)}")
print("***************************Menú gestion de jugador***************************")
print("1) Modificar mi jugador.")
print("2) Consulta un jugador.")
print("3) Eliminar mi jugador.")
print("Ingrese una opcion valida: 2")