print("***************************Menú Login de jugadores***************************")
print("1) Registro de nuevo jugador.")
print("2) Inicio sesion jugador.")
print("Ingrese una opcion valida: 1")
print("Cree el nombre de jugador nuevo: pabliotGamer")
print("Retorno a login.")
print("***************************Menú Login de jugadores***************************")
print("1) Registro de nuevo jugador.")
print("2) Inicio sesion jugador.")
print("Ingrese una opcion valida: 2")
print("Ingrese nombre de jugador: pabliotGamer")
print("***************************Login exitoso***************************")
print("Bienvenido pabliotGamer.")
print("Nivel: 1")
print("Puntaje: 1.000")
print("Equipo: En solitario")
print("Inventario: \n{[""AK-66""]: 30(160)  \n[""M9""]: 7(21) \n[""Botiquin""]: 1(3)}")
print("***************************Menú gestion de jugador***************************")
print("1) Modificar mi jugador.")
print("2) Consulta un jugador.")
print("3) Eliminar mi jugador.")
print("4) Inicia a jugar.")
print("Ingrese una opcion valida: 1")
print("Ingrese su nuevo nombre de jugador: pablitoElkiller")
print("Retorno a menu de gestionde jugador.")
print("***************************Menú gestion de jugador***************************")
print("1) Modificar mi jugador.")
print("2) Consulta un jugador.")
print("3) Eliminar mi jugador.")
print("4) Inicia a jugar.")
print("Ingrese una opcion valida: 2")
print("Ingrese el nombre del jugador a consultar: amigazoPro")
print("El susuario no existe.")
print("Retorno a menu de gestionde jugador.")
print("***************************Menú gestion de jugador***************************")
print("1) Modificar mi jugador.")
print("2) Consulta un jugador.")
print("3) Eliminar mi jugador.")
print("4) Inicia a jugar.")
print("Ingrese una opcion valida: 3")
print("Esta seguro de hacer esta accion: No ")
print("***************************Menú gestion de jugador***************************")
print("1) Modificar mi jugador.")
print("2) Consulta un jugador.")
print("3) Eliminar mi jugador.")
print("4) Inicia a jugar.")
print("Ingrese una opcion valida: 4")
print("ejemplo commit")
print("Ingrese una opcion valida: 2")


